patient/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
   path('patient', views.PatientLists, name="PatientLists"),
   path('patient_create', views.PatientCreate, name="PatientCreate"),
   path('patient_detailed/<patient_id>', views.PatientDetailed, name="PatientDetailed"),
   path('patient_edit/<patient_id>', views.PatientEdit, name="PatientEdit"),
   path('patient_delete', views.PatientDelete, name="PatientDelete"),

   path('patient_create_relative/<patient_id>', views.PatientCreateRelative, name="PatientCreateRelative"),
   path('patient_edit_relative/<relative_id>', views.PatientEditRelative, name="PatientEditRelative"),
   path('patient_remove_relative', views.PatientRemoveRelative, name="PatientRemoveRelative"),
   path('patient_get_relative', views.PatientGetRelative, name="PatientGetRelative"),


   path('patient_create_allergy/<patient_id>', views.PatientCreateAllergy, name="PatientCreateAllergy"),
   path('patient_delete_allergy', views.PatientDeleteAllergy, name="PatientDeleteAllergy"),

   path('patient_create_gps/<patient_id>', views.PatientCreateGPS, name="PatientCreateGPS"),
   path('patient_update_gps/<gps_id>', views.PatientUpdateGPS, name="PatientUpdateGPS"),
   path('patient_get_gps', views.PatientGetGPS, name="PatientGetGPS"),
   path('patient_autosave_gps', views.PatientAutoSaveGPS, name="PatientAutoSaveGPS"),
   path('patient_delete_gps/<int:gps_id>/', views.PatientDeleteGPS, name="PatientDeleteGPS"),

   path('patient_create_hamd/<patient_id>', views.PatientCreateHamD, name="PatientCreateHamD"),
   path('patient_update_hamd/<hamd_id>', views.PatientUpdateHamD, name="PatientUpdateHamD"),
   path('patient_get_hamd', views.PatientGetHamd, name="PatientGetHamd"),
   path('patient_autosave_hamd', views.PatientAutoSaveHamd, name="PatientAutoSaveHamd"),
   path('patient_delete_hamd/<int:hamd_id>/', views.PatientDeleteHamD, name="PatientDeleteHamD"),

   path('patient_survey/<patient_id>', views.PatientSurvey, name="PatientSurvey"),
   path('patient_view_survey/<patient_id>', views.PatientViewSurvey, name="PatientViewSurvey"),
   path('survey_completed', views.PatientSurveyCompleted, name="PatientSurveyCompleted"),

   path('patient_file_upload', views.PatientFileUpload, name="PatientFileUpload"),
   path('patient_referral_pdf/<int:referral_id>/', views.referralFormPdf, name='referralFormPdf'),
   
   # ICF (Informed Consent Form) related URLs
   path('check_icf_status/<int:patient_id>/', views.CheckICFStatus, name="CheckICFStatus"),
   path('upload_icf/', views.UploadICF, name="UploadICF"),
   path('preview_icf/<int:patient_id>/', views.PreviewICF, name="PreviewICF"),
   path('delete_icf/<int:patient_id>/', views.DeleteICF, name="DeleteICF"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# Create your models here.
class details(models.Model):
	first_name = models.CharField(max_length=250, null=True, blank=True)
	middle_name = models.CharField(max_length=250, null=True, blank=True)
	last_name = models.CharField(max_length=250, null=True, blank=True)
	gender = models.CharField(max_length=250, null=True, blank=True)
	gender_indentity = models.CharField(max_length=250, null=True, blank=True)
	BOD = models.DateField(null=True, blank=True)
	marital_status = models.CharField(max_length=250, null=True, blank=True)
	contact_number = models.CharField(max_length=250, null=True, blank=True)
	alias = models.CharField(max_length=250, null=True, blank=True)
	email = models.CharField(max_length=250, null=True, blank=True)
	birth_place = models.CharField(max_length=250, null=True, blank=True)
	religion = models.CharField(max_length=250, null=True, blank=True)
	high_education = models.CharField(max_length=250, null=True, blank=True)
	citizenship = models.CharField(max_length=250, null=True, blank=True)
	nationality = models.CharField(max_length=250, null=True, blank=True)
	workplace = models.CharField(max_length=250, null=True, blank=True)
	occupation = models.CharField(max_length=250, null=True, blank=True)
	profile_picture = models.FileField(upload_to='prof_pic/', null=True, blank=True)
	employment_status = models.CharField(max_length=250, null=True, blank=True)
	mental_health_history = models.CharField(max_length=250, null=True, blank=True)
	access_to_mental_health = models.CharField(max_length=250, null=True, blank=True)
	create_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now_add=True)
	history = models.TextField(null=True, blank=True)
	status = models.BooleanField(default=1)
	is_delete = models.BooleanField(default=0)

	@property
	def age(self):
		return int((datetime.now().date() - self.BOD).days / 365.25)

class address(models.Model):
	current_street = models.CharField(max_length=250, null=True, blank=True, default="")
	current_apt = models.CharField(max_length=250, null=True, blank=True, default="")
	current_barangay = models.CharField(max_length=250, null=True, blank=True, default="")
	current_province = models.CharField(max_length=250, null=True, blank=True, default="")
	current_city = models.CharField(max_length=250, null=True, blank=True, default="")
	current_country = models.CharField(max_length=250, null=True, blank=True, default="")
	current_zip_code = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_street = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_apt = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_barangay = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_province = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_city = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_country = models.CharField(max_length=250, null=True, blank=True, default="")
	ph_zip_code = models.CharField(max_length=250, null=True, blank=True, default="")
	create_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=1)
	is_delete = models.BooleanField(default=0)
	details = models.ForeignKey(details, null=True, blank=True, on_delete=models.SET_NULL)
	
class relatives(models.Model):
	first_name = models.CharField(max_length=250, null=True, blank=True)
	middle_name = models.CharField(max_length=250, null=True, blank=True)
	last_name = models.CharField(max_length=250, null=True, blank=True)
	gender = models.CharField(max_length=250, null=True, blank=True)
	gender_indentity = models.CharField(max_length=250, null=True, blank=True)
	DOB = models.DateField(null=True, blank=True)
	marital_status = models.CharField(max_length=250, null=True, blank=True)
	relationship = models.CharField(max_length=250, null=True, blank=True)
	high_education = models.CharField(max_length=250, null=True, blank=True)
	occupation = models.CharField(max_length=250, null=True, blank=True)
	Workplace = models.CharField(max_length=250, null=True, blank=True)
	contact_number = models.CharField(max_length=250, null=True, blank=True)
	email = models.CharField(max_length=250, null=True, blank=True)
	create_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now_add=True)
	history = models.TextField(null=True, blank=True)
	status = models.BooleanField(default=1)
	is_delete = models.BooleanField(default=0)
	details = models.ForeignKey(details, null=True, blank=True, on_delete=models.SET_NULL)
	is_emergency = models.BooleanField(default=0)

	@property
	def age(self):
		return int((datetime.now().date() - self.DOB).days / 365.25)

class medicine(models.Model):
	name = models.CharField(max_length=250, null=True, blank=True)
	status = models.BooleanField(default=1)
	is_delete = models.BooleanField(default=0)

class allergies(models.Model):
	medicine_name = models.ForeignKey(medicine, null=True, blank=True, on_delete=models.SET_NULL)
	details = models.ForeignKey(details, null=True, blank=True, on_delete=models.SET_NULL)
	is_delete = models.BooleanField(default=0)

class global_psychotrauma_screen(models.Model):
	EVENT_CHOICES = [
		('last week', 'last week'),
		('last month', 'last month'),
		('last half year', 'last half year'),
		('last year', 'last year'),
		('longer ago', 'longer ago'),
	]
	
	VIOLENCE_CHOICES = [
		('to yourself', 'to yourself'),
		('happened to someone else', 'happened to someone else'),
	]
	
	details = models.ForeignKey(details, null=True, blank=True, on_delete=models.SET_NULL)
	consultation_date = models.DateTimeField(auto_now_add=True)
	event_description = models.TextField(null=True, blank=True)
	event_happened = models.CharField(max_length=20, choices=EVENT_CHOICES, null=True, blank=True)
	physical_violence = models.CharField(max_length=30, choices=VIOLENCE_CHOICES, default='to yourself', null=True, blank=True)
	sexual_violence = models.CharField(max_length=30, choices=VIOLENCE_CHOICES, default='to yourself', null=True, blank=True)
	emotional_abuse = models.CharField(max_length=30, choices=VIOLENCE_CHOICES, default='to yourself', null=True, blank=True)
	serious_injury = models.CharField(max_length=30, choices=VIOLENCE_CHOICES, default='to yourself', null=True, blank=True)
	life_threatening = models.CharField(max_length=30, choices=VIOLENCE_CHOICES, default='to yourself', null=True, blank=True)
	sudden_death_of_loved_one = models.BooleanField(default=0)
	cause_harm_to_others = models.BooleanField(default=0)
	covid = models.BooleanField(default=0)
	single_event_occurring = models.CharField(max_length=250, null=True, blank=True)
	range_event_occurring_from = models.CharField(max_length=250, null=True, blank=True)
	range_event_occurring_to = models.CharField(max_length=250, null=True, blank=True)
	create_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now=True)
	history = models.TextField(null=True, blank=True)
	status = models.BooleanField(default=1)
	is_delete = models.BooleanField(default=0)
	
	class Meta:
		constraints = [
			models.CheckConstraint(
				check=~models.Q(details=None),
				name='gps_details_required'
			)
		]
	
	def clean(self):
		if not self.details:
			raise ValidationError('Details is required.')
		if self.event_happened and self.event_happened not in dict(self.EVENT_CHOICES):
			raise ValidationError('Invalid event_happened choice.')
	
	def save(self, *args, **kwargs):
		self.full_clean()
		# Always include update_date in update_fields if specified
		if 'update_fields' in kwargs and 'update_date' not in kwargs['update_fields']:
			kwargs['update_fields'] = list(kwargs['update_fields']) + ['update_date']
		super().save(*args, **kwargs)

class considering_event(models.Model):
	YES_NO_CHOICES = [
		('No', 'No'),
		('Yes', 'Yes'),
	]
	
	RATING_CHOICES = [
		('1', '1'),
		('2', '2'),
		('3', '3'),
		('4', '4'),
		('5', '5'),
		('6', '6'),
		('7', '7'),
		('8', '8'),
		('9', '9'),
		('10', '10'),
	]
	
	global_psychotrauma_screen = models.ForeignKey(global_psychotrauma_screen, null=True, blank=True, on_delete=models.CASCADE)
	considering_event_1 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_2 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_3 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_4 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_5 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_6 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_7 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_8 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_9 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_10 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_11 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_12 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)
	considering_event_13 = models.CharField(max_length=3, choices=YES_NO_CHOICES, default='No', null=False, blank=False)

patient/templates/patient_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Patient List {% endblock title %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<style type="text/css">
	.dashboard_welcome_greeting{
		color: #6417A1;
	}
	.card-header{
		background-color:#6417A180;
	}
	
</style>
{% endblock style %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<h2 class="dashboard_welcome_greeting">Patient Edit</h2>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-sm-1"></div>
		<div class="col-sm-10">
			<form id="Create_patient" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="card">
  					<div class="card-header">
    					<h4>Personal Information</h4>
  					</div>
  					<div class="card-body">
  						<div class="row">
							<style>
								.required-star {
									color: red;
								}
							</style>
  							<div class="col-sm-12">
  								{% if patientDetailed.profile_picture|length > 0 %}
                        			<img src="{{ patientDetailed.profile_picture.url|default_if_none:'#' }}" class="object-scale-down w-60 h-60 xl:w-40 xl:h-44 xl_4k:w-85 xl_4k:h-85 rounded-full" >
		                        {% endif %}
  							</div>
  							<div class="col-sm-6">
  								<div class="mb-3">
  									{{ form.profile_picture.label }}
                                	{{ form.profile_picture }}
								</div>
  							</div>
  						</div>
    					<div class="row">
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.first_name.label }}{% if form.first_name.field.required %}<span class="required-star">*</span>{% endif %}
									{{ form.first_name }}
									{% if form.first_name.errors %}
										<div class="text-danger">{{ form.first_name.errors }}</div>
									{% endif %}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.middle_name.label }}{% if form.middle_name.field.required %}*{% endif %}
    								{{ form.middle_name }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.last_name.label }}{% if form.last_name.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.last_name }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.gender.label }}{% if form.gender.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.gender }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.BOD.label }}{% if form.BOD.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.BOD }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.employment_status.label }}{% if form.employment_status.field.required %}*{% endif %}
    								{{ form.employment_status }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.mental_health_history.label }}{% if form.mental_health_history.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.mental_health_history }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.access_to_mental_health.label }}{% if form.access_to_mental_health.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.access_to_mental_health }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.marital_status.label }}{% if form.marital_status.field.required %}*{% endif %}
    								{{ form.marital_status }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.contact_number.label }}{% if form.contact_number.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.contact_number }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.alias.label }}{% if form.alias.field.required %}*{% endif %}
    								{{ form.alias }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div  class="form-group">
    								{{ form.email.label }}{% if form.email.field.required %}<span class="required-star">*</span>{% endif %}
    								{{ form.email }}
  								</div>
    						</div>
    					</div>
    				</div>
				</div>
				<br>
				<div class="card">
  					<div class="card-header">
    					<h4>Personal Address</h4>
  					</div>
  					<div class="card-body">
    					<h5>Current Address</h5>
    					<div class="row">
    						<div class="col-sm-8">
    							<div class="form-group">
    								{{ FormEditPatientAddress.current_street.label }}{% if FormEditPatientAddress.current_street.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.current_street }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.current_apt.label }}{% if FormEditPatientAddress.current_apt.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.current_apt }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.current_city.label }}{% if FormEditPatientAddress.current_city.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.current_city }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.current_country.label }}{% if FormEditPatientAddress.current_country.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.current_country }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.current_zip_code.label }}{% if FormEditPatientAddress.current_zip_code.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.current_zip_code }}
  								</div>
    						</div>
    					</div>
    				</div>
    				<div class="card-body">
    					<h5>Philippine Address</h5>
    					<div class="row">
    						<div class="col-sm-8">
    							<div class="form-group">
    								{{ FormEditPatientAddress.ph_street.label }}{% if FormEditPatientAddress.ph_street.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.ph_street }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.ph_barangay.label }}{% if FormEditPatientAddress.ph_barangay.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.ph_barangay }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.ph_province.label }}{% if FormEditPatientAddress.ph_province.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.ph_province }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.ph_city.label }}{% if FormEditPatientAddress.ph_city.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.ph_city }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ FormEditPatientAddress.ph_zip_code.label }}{% if FormEditPatientAddress.ph_zip_code.field.required %}*{% endif %}
    								{{ FormEditPatientAddress.ph_zip_code }}
  								</div>
    						</div>
    					</div>
    					{{ FormEditPatientAddress.ph_country }}
    				</div>
    				
				</div>
				<div class="card">
  					<div class="card-header">
    					<h4>Other Detail</h4>
  					</div>
  					<div class="card-body">
    					<div class="row">
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.birth_place.label }}{% if form.birth_place.field.required %}*{% endif %}
    								{{ form.birth_place }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.religion.label }}{% if form.religion.field.required %}*{% endif %}
    								{{ form.religion }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.high_education.label }}{% if form.high_education.field.required %}*{% endif %}
    								{{ form.high_education }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.nationality.label }}{% if form.nationality.field.required %}*{% endif %}
    								{{ form.nationality }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.workplace.label }}{% if form.workplace.field.required %}*{% endif %}
    								{{ form.workplace }}
  								</div>
    						</div>
    						<div class="col-sm-4">
    							<div class="form-group">
    								{{ form.occupation.label }}{% if form.occupation.field.required %}*{% endif %}
    								{{ form.occupation }}
  								</div>
    						</div>
    					</div>
    				</div>
				</div>
				<br/>
				<div class="row justify-content-md-center">
				    <div class="col-md-auto">
				      <button type="submit" class="btn btn-outline-success add_patient_btn">Update Patient</button>
				      <a href="{% url 'PatientDetailed' patientDetailed.pk %}" style="text-decoration:none;">
				      <button type="button" class="btn btn-outline-secondary">Cancel</button>
				      </a>
				    </div>
  				</div>
				<br/><br/>
			</form>
		</div>
		<div class="col-sm-1"></div>
	</div>
</div>
{% endblock content %}


{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script type="text/javascript">
	var provinces = [
                "ABRA", "AGUSAN DEL NORTE", "AGUSAN DEL SUR", "AKLAN", "ALBAY", "ANTIQUE",
                "APAYAO", "AURORA", "BASILAN", "BATAAN", "BATANES", "BATANGAS", "BENGUET",
                "BILIRAN", "BOHOL", "BUKIDNON", "BULACAN", "CAGAYAN", "CAMARINES NORTE",
                "CAMARINES SUR", "CAMIGUIN", "CAPIZ", "CATANDUANES", "CAVITE", "CEBU",
                "COTABATO", "DAVAO DE ORO", "DAVAO DEL NORTE", "DAVAO DEL SUR",
                "DAVAO OCCIDENTAL", "DAVAO ORIENTAL", "DINAGAT ISLANDS", "EASTERN SAMAR",
                "GUIMARAS", "IFUGAO", "ILOCOS NORTE", "ILOCOS SUR", "ILOILO",
                "ISABELA", "KALINGA", "LA UNION", "LAGUNA", "LANAO DEL NORTE",
                "LANAO DEL SUR", "LEYTE", "MAGUINDANAO DEL NORTE", "MAGUINDANAO DEL SUR",
                "MARINDUQUE", "MASBATE", "MISAMIS OCCIDENTAL", "MISAMIS ORIENTAL",
                "MOUNTAIN PROVINCE", "NEGROS OCCIDENTAL", "NEGROS ORIENTAL",
                "NORTHERN SAMAR", "NUEVA ECIJA", "NUEVA VIZCAYA", "OCCIDENTAL MINDORO",
                "ORIENTAL MINDORO", "PALAWAN", "PAMPANGA", "PANGASINAN", "QUEZON",
                "QUIRINO", "RIZAL", "ROMBLON", "SAMAR", "SARANGANI", "SIQUIJOR",
                "SORSOGON", "SOUTH COTABATO", "SOUTHERN LEYTE", "SULTAN KUDARAT",
                "SULU", "SURIGAO DEL NORTE", "SURIGAO DEL SUR", "TARLAC", "TAWI-TAWI",
                "ZAMBALES", "ZAMBOANGA DEL NORTE", "ZAMBOANGA DEL SUR", "ZAMBOANGA SIBUGAY", "NATIONAL CAPITAL REGION", "SOCCSKSARGEN"
            ];
		$("#id_ph_province").autocomplete({
        	source: provinces
        });
        var birth_place = ["NCR", "CAR", " Region I (Ilocos)", "Region II (Cagayan Valley)", "Region III (Central Luzon)", "Region IV-A (Calabarzon)",
        "Region IV-B (MiMaRoPa)",  "Region V (Bicol)", "Region VI (Western Visayas)", "NIR (Negros Island Region)", "Region VII (Central Visayas)",
    	"Region VIII (Eastern Visayas)", "Region IX (Zamboanga Peninsula)", "Region X (Northern Mindanao)", "Region XI (Davao Region)", "Region XII (Soccsksargen)",
    	"Region XIII (Caraga Region)",  "BARMM"];
    	$("#id_birth_place").autocomplete({
    		source: birth_place
    	});
    	const religions = [ "Catholic", "Protestant", "Christianity", "Islam", "Hinduism", "Buddhism", "Sikhism", "Judaism", "Atheism", "Agnosticism", "Deism", "Pantheism", "No religion"];
    	$("#id_religion").autocomplete({
    		source: religions
    	});

    	const educationLevels = [ "Elementary", "High school", "College", "Vocational", "Post graduate", "ALS"];
    	$("#id_high_education").autocomplete({
    		source: educationLevels
    	});

    	const occupation = [ "household service worker", "skilled worker", "homemaker", "none"];
    	$("#id_occupation").autocomplete({
    		source: occupation
    	});
	
</script>
{% endblock script %}